### ISSUE TITLE
meter neurocirujanos en piloto de testing

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#13]
Al parecer, CSW puede llegar a verse como más común que SIADH en neurocirugía. Igual tiene sentido que lo utilicen neurocirujanos para esos casos:

B. Palmer, Hyponatremia in patients with central nervous system disease: SIADH versus CSW (2003)

**Comment by cuestamartin** [comment]
No. 

En estudios prospectivos en Dublin y en otros centros se ha demostrado que el CSW es rarísimo, y habitualmente mal diagnosticado. 
Esa afirmación no es cierta. 

J Clin Endocrinol Metab. 2014 Jan;99(1):291-8. doi: 10.1210/jc.2013-3032. Epub 2013 Dec 20.
Hyponatremia following mild/moderate subarachnoid hemorrhage is due to SIAD and glucocorticoid deficiency and not cerebral salt wasting.
Hannon MJ1, Behan LA, O'Brien MM, Tormey W, Ball SG, Javadpour M, Sherlock M, Thompson CJ.
Author information
Erratum in
J Clin Endocrinol Metab. 2014 Mar;99(3):1096. Javadpur, M [corrected to Javadpour, M].
Abstract
CONTEXT:
Hyponatremia is common after acute subarachnoid hemorrhage (SAH) but the etiology is unclear and there is a paucity of prospective data in the field. The cause of hyponatremia is variously attributed to the syndrome of inappropriate antidiuresis (SIAD), acute glucocorticoid insufficiency, and the cerebral salt wasting syndrome (CSWS).
OBJECTIVE:
The objective was to prospectively determine the etiology of hyponatremia after SAH using sequential clinical examination and biochemical measurement of plasma cortisol, arginine vasopressin (AVP), and brain natriuretic peptide (BNP).
DESIGN:
This was a prospective cohort study.
SETTING:
The setting was the National Neurosurgery Centre in a tertiary referral centre in Dublin, Ireland.
PATIENTS:
One hundred patients with acute nontraumatic aneurysmal SAH were recruited on presentation.
INTERVENTIONS:
Clinical examination and basic biochemical evaluation were performed daily. Plasma cortisol at 0900 hours, AVP, and BNP concentrations were measured on days 1, 2, 3, 4, 6, 8, 10, and 12 following SAH. Those with 0900 hours plasma cortisol<300 nmol/L were empirically treated with iv hydrocortisone.
MAIN OUTCOME MEASURES:
Plasma sodium concentration was recorded daily along with a variety of clinical and biochemical criteria. The cause of hyponatremia was determined clinically. Later measurement of plasma AVP and BNP concentrations enabled a firm biochemical diagnosis of the cause of hyponatremia to be made.
RESULTS:
Forty-nine of 100 developed hyponatremia<135 mmol/L, including 14/100<130 mmol/L. The cause of hyponatremia, and determined by both clinical examination and biochemical hormone measurement, was SIAD in 36/49 (71.4%), acute glucocorticoid insufficiency in 4/49 (8.2%), incorrect iv fluids in 5/49 (10.2%), and hypovolemia in 5/49 (10.2%). There were no cases of CSWS.
CONCLUSIONS:
The most common cause of hyponatremia after acute nontraumatic aneurysmal SAH is SIAD. Acute glucocorticoid insufficiency accounts for a small but significant number of cases. We found no cases of CSWS.

**Comment by cuestamartin** [comment]
Los neurocirujanos no tienen ni idea, ni interés en esta patología. Consultan siempre a Endocrinología o Nefrología.
No creo que sea de ninguna utilidad. La gran mayoría no sabe lo que es ( no es broma)

**Comment by arturogf** [comment]
Ok!
