### ISSUE TITLE
duda baja ingesta de solutos

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#70]
aunque está clasificada como euvolémica puede ser hipovolémica y por eso los argumentos de hipovolemia no van ni favor ni en contra. ¿¿¿¿ y los de analítica, porque hay dos en contra??? ¿está bien así?

**Comment by cuestamartin** [comment]
La realidad es que este es un diagnóstico difícil de explicar o definir en la vida real. Copio de la guía. 

Efectivamente puede ser tanto euvolémica como hipovolémica. Aunque se suele ver más en euvolémicos. Ejemplo: bebedores de cerveza, grandes bebedores de te...que luego comen muy poco e ingieren poca sal. 
Sin embargo, ocasionalmente también se ve en pacientes que restrinjan muchísimo la ingesta de agua y sal, pero más de sal que de agua. Ejemplo: anorexia nerviosa en algunas ocasiones no siempre. 

Por lo que veo los que van en contra son porque los clasifican como hipovolémico ( aumento de creatinina o urea). Es decir, porque debimos de decidir que era euvolémica sí o sí. 
Y quizás es lo más práctico. Es un cuadro raro y la guía la clasifica sí o sí como euvolémica. Es un caso particularmente difícil porque no está ni bien estudiado en la literatura ni caracterizado bioquímicamente. 

De hecho yo quitaría que OsmU>100 es -1. He visto casos de esas características y típicamente tienen entre 100-200 mOsm/kg de OsmU. Pero evidencia muy muy poca al respecto, muy poco descrito en la literatura. 

Yo seguiría la guía en este diagnóstico y no pondría que pueden estar hipovolémicos si ni comen ni beben, aunque en ocasiones ( anorexia nerviosa o paciente con cancer avanzado) sí que se pueda ver. Si queremos diagnosticar más que la guía entonces sí, tenemos que concebir que es euvolémica e hipovolémica (opinión de expertos). 

Propongo seguir la guía en este punto. 

Dicho esto la guía la clasifica como euvolémica. 

candidate :: 'LowSoluteIntake' ;
argument :: 1.0,Na_ur < 20  
argument :: -((1.0)),Na_ur >= 20  
argument :: 1.0,AscEd="No"  
argument :: 1.0,DietaHabitos includes "Come poco"  
argument :: 1.0,DietaHabitos includes "Alcohol en exceso"  
argument :: -((5.0)),DietaHabitos includes "Come normal"  
argument :: -((10.0)),(AscEd="Yes") AND (FuncionRenal = "Normal") AND (InsufCardiaca  = "No" )  
argument :: 1.0,OSM_ur  =< 100  
argument :: -((1.0)),OSM_ur > 100  
argument :: -((1.0)),(BUN > 20)  
argument :: -((1.0)),(Creatinina_ser>1.1 AND Sexo="Mujer") OR (Creatinina_ser>1.3 AND Sexo="Hombre") AND (FuncionRenal = "Normal")  

Low Solute Intake. Some cases of euvolemic hyponatremia
do not fit particularly well into either a euvolemic or
hypovolemic category. Among these is the hyponatremia
that sometimes occurs in patients who ingest large volumes
of beer with little food intake for prolonged periods (beer
potomania). Even though the volume of fluid ingested may
not seem sufficiently excessive to overwhelm renal-diluting
mechanisms, in these cases, solute-free water excretion is
limited by very low urine solute excretion as a result of the
low solute content of beer, because 50 mOsmol of urinary
solute excretion are required to excrete each liter of maximally
dilute urine. Because of this, water retention and
hyponatremia will result when fluid intake exceeds the
maximum volume of urine that can be excreted based on the
available urine solute.87 Similar cases have been reported in
patients on very-low-protein diets88 or who restrict themselves
to “tea and toast” diets; both these diet types are also
low in solute content. Because urine osmolality is typically
Verbalis et al Hyponatremia Treatment S15
very low in such patients, there is no significant role for
AVP in producing the hyponatremia.

**Comment by arturogf** [comment]
Eliminamos el argumento en contra:

argument :: -((1.0)),OSM_ur > 100

En la guía dice que la OSM_ur es típicamente muy baja, por lo tanto dejamos el a favor.
